apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aisdlc-orchestrator.fullname" . }}-config
  labels:
    {{- include "aisdlc-orchestrator.labels" . | nindent 4 }}
data:
  DEPLOY_ENV:              {{ .Values.env.DEPLOY_ENV | default "dev" | quote }}
  AWS_REGION:              {{ .Values.env.AWS_REGION | default "us-east-1" | quote }}
  AGENT_MAX_RETRY:         {{ .Values.env.AGENT_MAX_RETRY | default "2" | quote }}
  GITHUB_OWNER:            {{ .Values.env.GITHUB_OWNER | default "bhaskarmca83" | quote }}
  JIRA_BASE_URL:           {{ .Values.env.JIRA_BASE_URL | default "https://bhaskarwork.atlassian.net" | quote }}
  CONFLUENCE_BASE_URL:     {{ .Values.env.CONFLUENCE_BASE_URL | default "https://bhaskarwork.atlassian.net/wiki" | quote }}
  CONFLUENCE_PARENT_PAGE:  {{ .Values.env.CONFLUENCE_PARENT_PAGE | default "524458" | quote }}
  FRONTEND_ORIGIN:         {{ .Values.env.FRONTEND_ORIGIN | default "http://localhost:5173" | quote }}
  LOG_LEVEL:               {{ .Values.env.LOG_LEVEL | default "INFO" | quote }}
